---
title: "Music Data Processing"
author: "Lester Huang, Eric Osterman, Ethan Lavi, Emma Closter, Gabrielle Effendi"
date: "11/15/2022"
output: html_notebook
---

```{r}
library(e1071)
library(pROC)
```


Load the train and test data
```{r}
train = read.csv("./train.csv", header=TRUE)
test = read.csv("./test.csv", header=TRUE)

# Remove index column
train$X <- NULL
test$X <- NULL

source("classPredictions.R")
```

Train models and select best based on 10-fold CV
```{r}
# Create 10 equally sized folds
folds <- cut(seq(1, nrow(test)), breaks=10, labels=FALSE)
alpha <- 1
index <- 1
metrics <- data.frame(Alpha=double(), Accuracy=double(), AROC=double())

for (alpha in c(0.1, 1, 10, 100, 1000, 10000)) {
  
  aggr_acc <- 0
  aggr_roc <- 0
  
  # Begin 10-fold CV
  for (i in 1:10) {
    # Segment data by folds using which()
    testIndices <- which(folds == i, arr.ind=TRUE)
    validateSet <- train[testIndices, ]
    trainSet <- train[-testIndices, ]
    
    #  Separate into X and Y vars
    trainX <- trainSet
    trainX$genre <- NULL
    trainY <- as.factor(trainSet$genre)
    
    validateX <- validateSet
    validateX$genre <- NULL
    validateY <- as.factor(validateSet$genre)
    
    # Train Model
    model <- naiveBayes(trainX, trainY, laplace=alpha)
    pred <- predict(model, validateX, type="class")
    
    conf_matrix <- table(pred, validateY)
    
    # Compute metrics
    acc <- sum(diag(conf_matrix))/sum(conf_matrix)
    roc <- multiclass.roc(as.numeric(validateY), as.numeric(pred), quiet=TRUE)$auc
    
    aggr_acc <- aggr_acc + sum(diag(conf_matrix))/sum(conf_matrix)
    aggr_roc <- aggr_roc + multiclass.roc(as.numeric(validateY), as.numeric(pred), quiet=TRUE)$auc
    
  }
  
  metrics[index, ] <- c(alpha, aggr_acc / 10, aggr_roc / 10)
  index <- index + 1
}

print(metrics)
```

Predict on Test Values
```{r}
# Select model with alpha = 1000, produced best results in training
testY <- test$genre
testX <- test
testX$genre <- NULL

model <- naiveBayes(trainX, trainY, laplace=1000)
pred <- predict(model, testX, type="class")

predictive_values(testY, pred)
```


Plot ROC Curve with selected model
```{r}
source("rocCurve.R")

predProb <- predict(model, testX, type="class")
make_roc(predProb, testY, "Naive Bayes")
```

